title: Site Options
pages:
  template:
    - default
    - home
    - archive
files: true
fields:
  # Site Settings
  title:
    label: Site Name
    type: text

  # Current Term

  section_current:
    label: Current Settings
    type: headline

  current_term:
    label: Current Term
    type: select
    options: query    
    query:
      page: archive
      fetch: grandchildren
      value: '{{uri}}'
      text: '{{parentTitle}} — {{title}}'
    required: true

  section_meta:
    label: Metadata + Search
    type: headline
  meta_description:
    label: Site Description
    type: text
    help: A blurb about the site. This will appear in search results and social previews.
  meta_subject:
    label: Site Subject
    type: text
    help: A more succinct version of the above, if available, for bots.
  meta_keywords:
    label: Site Keywords
    type: tags
  meta_image:
    label: Site Preview Image
    type: image
  meta_analytics_id:
    label: Google Analytics Tracking ID
    type: text
  meta_favicon:
    label: Favicon
    type: image

  # Footer
  section_footer:
    label: Footer Content
    type: headline
  about:
    label: About Fresh
    type: textarea
    help: >
      More general description of what Fresh is. Not specific to any term.
  alumni_preview:
    label: Alumni Archive Preview
    type: textarea
